import tkinter as tk
from tkinter import IntVar,END
from PIL import Image, ImageTk
root = tk.Tk()
root.geometry('400x400')
root.resizable(False, False)
root.title('Calculator')
default_bg = root.cget("bg")
image = Image.open("C:\\Users\\Manisha\\Downloads\\calcu.png")
width = 400
height = 400
resized_image = image.resize((width, height))
photo = ImageTk.PhotoImage(resized_image)
label0 = tk.Label(root, image = photo)
label0.place(x=0, y=0, relheight=1, relwidth=1)
label1 = tk.Label(root, text='CALCULATOR', font=('Times New Roman', 18), bg= default_bg)
label1.place(x=120,y=10)
label2 = tk.Label(root, text='Enter 1st number  :', font=('Times New Roman',14), bg= default_bg)
label2.place(x=10,y=80)
label3 = tk.Label(root, text='Enter 2nd number :', font=('Times New Roman',14), bg= default_bg)
label3.place(x=10,y=120)
num1 = IntVar()
num2 = IntVar()
entry1 = tk.Entry(root, textvariable=num1, font=('Times New Roman', 12))
entry1.place(x=180,y=80)
entry2 = tk.Entry(root, textvariable=num2, font=('Times New Roman', 12))
entry2.place(x=180,y=120)
def add():
    sum = num1.get()+num2.get()
    entry3.delete(0, END)
    entry3.insert(0, str(sum))
def sub():
    diff = num1.get()-num2.get()
    entry3.delete(0, END)
    entry3.insert(0, str(diff))
def mul():
    pro = num1.get()*num2.get()
    entry3.delete(0, END)
    entry3.insert(0, str(pro))
def div():
    quo = num1.get()/num2.get()
    entry3.delete(0, END)
    entry3.insert(0, str(quo))
button1 = tk.Button(root, text= '+', command=add, width=10, bg='light blue')
button1.place(x=80,y=200)
button2 = tk.Button(root, text= '-', command=sub, width=10, bg='light blue')
button2.place(x=250,y=200)
button3 = tk.Button(root, text= '*', command=mul, width=10, bg='light blue')
button3.place(x=80,y=250)
button4 = tk.Button(root, text= '/', command=div, width=10, bg='light blue')
button4.place(x=250,y=250)
label4 = tk.Label(root, text='Result', font=('Times New Roman', 14), bg= default_bg)
label4.place(x=185, y=300)
entry3 = tk.Entry(root, font=('Times New Roman', 12))
entry3.place(x=135, y=350)
root.mainloop()